<div class="footer_bottom">
    <div class="section_wrapper">
        <div class="inner">
            <div class="inner_box">
                <h4 class="footer_heading">
                    <?= __('Footer Heading'); ?>
                </h4>
                <ul>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="inner_box">
                <h4 class="footer_heading">
                    <?= __('Footer Heading'); ?>
                </h4>
                <ul>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="inner_box">
                <h4 class="footer_heading">
                    <?= __('Footer Heading'); ?>
                </h4>
                <ul>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="inner_box">
                <h4 class="footer_heading">
                    <?= __('Footer Heading'); ?>
                </h4>
                <ul>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link">
                        <?= __('Links Link'); ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="inner connect">
            <h4 class="footer_heading">
                <?= __('Connect with us'); ?>
            </h4>
            <div class="social_links">
                <a href="#" class="social link facebook" title="Facebook">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#" class="social link linkedin" title="Linkedin">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a href="#" class="social link twitter" title="Twitter">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#" class="social link instagram" title="Instagram">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>   
        </div>
    </div>
</div>

