<section class="section banner">
    <div class="section_wrapper">
        <div class="theme_slider">
            <div class="owl-carousel owl-theme" id="owlslider">
                <div class="item">
                    <a href="#">
                    <img src="<?= $this->getViewFileUrl('Theme_Banner/images/banner1.jpg'); ?>" alt="banner">
                    </a>
                </div>
                <div class="item">
                    <a href="#">
                    <img src="<?= $this->getViewFileUrl('Theme_Banner/images/banner2.jpg'); ?>" alt="banner">
                    </a>
                </div>
                <div class="item">
                    <a href="#">
                    <img src="<?= $this->getViewFileUrl('Theme_Banner/images/banner3.jpg'); ?>" alt="banner">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    require(["jquery","owlcarousel"],function($) {
        $(document).ready(function() {
            $("#owlslider").owlCarousel({
                navigation : true,
                autoPlay: false,
                items : 1
            });
        });
    });
</script>