<section class="section service_list">
    <div class="section_wrapper">
        <a href="#" class="link service_link">
            <i class="fas fa-shipping-fast"></i>
            <span>
                <?= __('Free Shipping'); ?>
            </span>
        </a>
        <a href="#" class="link service_link">
            <i class="far fa-life-ring"></i>
            <span>
                <?= __('Free Support'); ?>
            </span>
        </a>
        <a href="#" class="link service_link">
            <i class="fas fa-headset"></i>
            <span>
            <?= __('Support 24/7'); ?>
            </span>
        </a>
        <a href="#" class="link service_link">
            <i class="fas fa-door-open"></i>
            <span>
                <?= __('Door Service'); ?>
            </span>
        </a>
        <a href="#" class="link service_link">
            <i class="fas fa-skiing"></i>
            <span>
                <?= __('Fast Service'); ?>
            </span>
        </a>
    </div>
</section>